apiVersion: v2
name: admiral-k8s-agent
description: Admiral Kubernetes agent — connects a cluster to the Admiral control plane.
icon: https://charts.admiral.io/logo.png
type: application
version: 0.4.0
appVersion: v0.1.0
maintainers:
  - name: Admiral Contributors
    url: https://github.com/admiral-io/admiral-helm
