apiVersion: v2
name: admiral-k8s-agent
description: Connects a Kubernetes cluster to Admiral.
icon: https://charts.admiral.io/logo.png
type: application
version: 0.5.0
appVersion: v0.1.0
maintainers:
  - name: Admiral Contributors
    url: https://github.com/admiral-io/admiral-helm
