{{- if and (not .Values.agent.existingSecret) .Values.agent.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admiral-k8s-agent.tokenSecretName" . }}
  labels:
    {{- include "admiral-k8s-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  runner-token: {{ .Values.agent.token | quote }}
{{- end }}
