{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "admiral.postgres.fullname" . }}
  labels:
    {{- include "admiral.postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
      protocol: TCP
  selector:
    {{- include "admiral.postgres.selectorLabels" . | nindent 4 }}
{{- end }}
