{{- if and (not .Values.postgresql.enabled) (not .Values.externalDatabase.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-externaldb" (include "admiral.fullname" .) }}
  labels:
    {{- include "admiral.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ .Values.externalDatabase.password | default "" | b64enc | quote }}
{{- end }}
