name: Chart Publish

on:
  push:
    branches:
      - master
    paths:
      - "charts/**"

permissions:
  contents: read

jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: Setup Helm
        uses: azure/setup-helm@dda3372f752e03dde6b3237bc9431cdc2f7a02a2 # v5.0.0
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Add Helm repositories
        run: |
          helm repo add minio https://charts.min.io
          helm repo update
      - name: Build chart dependencies
        run: |
          for chart in charts/*/; do
            if [ -f "$chart/Chart.lock" ]; then
              helm dependency build "$chart"
            fi
          done
      - name: Prepare PGP key
        run: |
          IFS=""
          echo "$PGP_PRIVATE_KEY" | gpg --dearmor > $HOME/secring.gpg
          echo "$PGP_PASSPHRASE" > $HOME/passphrase.txt

          # Tell chart-releaser-action where to find the key and its passphrase
          echo "CR_KEYRING=$HOME/secring.gpg" >> "$GITHUB_ENV"
          echo "CR_PASSPHRASE_FILE=$HOME/passphrase.txt" >> "$GITHUB_ENV"
        env:
          PGP_PRIVATE_KEY: ${{ secrets.PGP_PRIVATE_KEY }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          config: "./.github/configs/cr.yaml"
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to GHCR
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 # v4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push chart to GHCR
        run: |
          shopt -s nullglob
          repo=$(echo "${{ github.repository }}" | awk '{print tolower($0)}')
          for pkg in .cr-release-packages/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/"${repo}"
          done
